name: propmolflow
channels:
  - pytorch
  - nvidia
  - pyg
  - dglteam/label/cu124
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.7.1+cu128
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - pytorch-cluster=1.6.3+pt27cu128
  - pytorch-scatter=2.1.2+pt27cu128
  - dgl=2.4.0+cu124
  - pytorch-lightning=2.5.2
  - rdkit=2025.3.3
  - pystow
  - einops
  - pip
  - pip:
      - wandb
      - useful_rdkit_utils
      - py3Dmol
      - ase
